export * from './material/custom.material.module';
export * from './material/o-mat-error/o-mat-error';
export * from './components/dialog/o-dialog.component';
export * from './components/dialog/o-dialog.config';
export * from './components/error403/o-error-403.component';
export * from './components/snackbar/o-snackbar.component';
export * from './components/validation/o-error.component';
export * from './components/validation/o-validator.component';
export * from './shared.module';
