---
name: Release Preview

concurrency:
  group: release-preview
  cancel-in-progress: true

on:
  pull_request:
    types: [labeled, synchronize]
    branches: ['master']
    paths: ['projects/ontimize-web-ngx/**']

jobs:
  release-preview:
    name: Release Preview
    if: contains(join(github.event.pull_request.labels.*.name, ', '), 'release')
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Node 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.13.0
          registry-url: ${{ env.NPM_REGISTRY }}

      - name: obtain package.json version
        id: project
        run: |
          echo ::set-output name=version::$(node -pe "require('./package.json')['version']")
          echo "RELEASE_VERSION=$(node -pe "require('./package.json')['version']")" >> $GITHUB_ENV

      - name: abort if SNAPSHOT
        if: "contains(steps.project.outputs.version, 'SNAPSHOT')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "FAILURE_MESSAGE=Your release version **is an SNAPSHOT and it needs to be fixed to make a release!**
          The release version detected was: $RELEASE_VERSION" >> $GITHUB_ENV
          exit 1

      - name: npm install and npm run build
        run: |
          echo "FAILURE_MESSAGE=The build process has failed" >> $GITHUB_ENV
          npm i
          npm run build

      - name: Add PR comment with release preview
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MESSAGE="
          ### :rocket: Release Preview Success
          You are going to release the version **$RELEASE_VERSION**!!

          ### 💡 Merge Strategy: Create a merge commit
          "
          gh pr comment ${{ github.event.number }} --body "$(echo -e "$MESSAGE")"

      - name: Add PR comment on Failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.number }} --body "
          ### :exclamation: :exclamation: :exclamation: Release Preview Failure
          There has been an error whilst checking requirements for release version.

          ### 💡 Required work to continue with the release
          $FAILURE_MESSAGE
          "


